name: GitLint

on:
  push:
  pull_request:

jobs:
  gitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Lint commits, branches, and pull requests
        uses: aschbacd/gitlint-action@v1.2.0
        with:
          re-branch-name: "^(main|master|(feature|fix|refactor|docs|test|chore)/.+)$"
          re-commit-message-subject: '^(feat|fix|refactor|docs|test|chore)(\([a-z0-9-]+\))?: .+'
